### ISSUE TITLE
echoing the exit code of the forced task

### ISSUE THREAD

**Issue by kylezeeuwen** [floriangosse/grunt-force-task#2]
Hi,

Thanks for the code.

I needed to use the following pattern to get the desired behaviour in CI : http://stackoverflow.com/a/37874843/3344695

Thought I would share here in case anyone else comes looking for a solution. 

If I submitted a pull request with an addition to the docs would you accept it ?

**Comment by floriangosse** [comment]
Why do you want that the following tasks should be executed after one forced task failed? You can replace `force:your-task` with `your-task` and it will fail there.

**Comment by kylezeeuwen** [comment]
In my case I want the following tasks to execute because the following task is a clean up task that must run, regardless of whether `your-task` passes or fails.

 `grunt-force-task` allows the following task to always run, which is good. But if I use force:your-task the grunt process exit code is always 0, regardless of whether `your-task` passes or fails. I need the grunt process exit code to match the pass/fail status of `your-task`.

**Comment by floriangosse** [comment]
If I didn't overlook anything you need to add an extra task for it. And I think this is not the task of `grunt-force-task`.

**Comment by deckar01** [comment]
@kylezeeuwen That solution doesn't seem to be working for me. I am using jasmine to run unit tests, and need to generate the coverage report even if the tests fail. Your solution just causes an additional task to output the warning without actually failing the task.

~~@floriangosse The issue seems to be that resetting `force` in the post task can't change the fact that the task gets stored as a success. Listing the task as a dependency without the force prefix resolves to a task that grunt thinks succeeded. It would be nice if this library caught the task exception instead of setting the `force` option so that the underlying task would not get marked as a success.~~

**Update:** It is not working for me, because I am forcing a multitask. Although the subtask it not added to the success list, the parent multitask still is.

``` js
grunt.loadNpmTasks('grunt-force-task');
grunt.loadNpmTasks('grunt-contrib-jasmine');
grunt.loadNpmTasks('grunt-istanbul-combine');

grunt.registerTask('test', function() {
  grunt.task.run('force:jasmine');
  grunt.task.run('istanbul_combine');
  grunt.task.run('jasmine-passed');
});

grunt.registerTask('jasmine-passed', function() {
  this.requires('jasmine');
});
```

My real tasks pass through the subtask which causes the `requires` statement to more specifically  target the task that actually failed (so it works as long as the target is not a multitask).

I think this is a grunt bug. Even if force is enabled, a multitask should not be marked as success if a child task fails.

**Comment by kylezeeuwen** [comment]
Hi @floriangosse , sorry for the delay. I agree that "this is not the task of `grunt-force-task` so am happy to close the issue. 

I raised the issue so we can consider if it is worth documenting the "grunt success/fail behaviour" when using grunt-force-task, and to point users at solutions if they have use cases like the one I describe

**Comment by kylezeeuwen** [comment]
Hi @deckar01 , in my use case I was interested in the exit code of the grunt process. I would like to know, in your scenario, whether you are getting a 0 or non-zero exit code when `jasmine` fails.

Apologies if this is obvious but to quickyl review exit code checking in a *nix environment

```
Kyles-MacBook-Pro:~ kyle$ true
Kyles-MacBook-Pro:~ kyle$ echo $?
0

Kyles-MacBook-Pro:~ kyle$ false
Kyles-MacBook-Pro:~ kyle$ echo $?
1

Kyles-MacBook-Pro:~ kyle$ grunt test
Kyles-MacBook-Pro:~ kyle$ echo $?
<WHAT IS THE VALUE HERE> ??
```

**Comment by deckar01** [comment]
- With `grunt-force` alone I am getting a 0 exit code.
- If I use your fix on a single task I get a non-zero exit code. :ok_hand:
- If I use your fix on a multitask I get a 0 exit code :disappointed: (because grunt marked the multitask as a success).

I am kicking off the grunt task with an npm script which produces a nice long error message when the exit code is non-zero.

**Comment by kylezeeuwen** [comment]
Ok I understand, interesting ! And unfortunate :( I'll have a play update the official docs (stack overflow) .

**Comment by deckar01** [comment]
FWIW I moved my "delayed failure" logic into the npm script and stopped using `grunt-force-task`.

``` sh
grunt test; STATUS=$?; grunt istanbul_combine; exit $STATUS
```

Not ideal, but not unbearable.
